openapi: 3.0.3
info:
  x-api-type: Shopper
  x-api-family: Custom Object
  title: Shopper Custom Objects
  version: 1.0.10
  description: |-
    [Download API specification](https://developer.salesforce.com/static/commercecloud/commerce-api/shopper-custom-objects/shopper-custom-objects-oas-v1-public.yaml)

    # API Overview

    Custom Objects hold configuration information that is unique to your business, such as third-party configuration information or special field values for Product Information Management (PIM) systems.

    For example, if your out-of-the-box B2C Commerce product attributes do not include employee ID information, you can create a custom attribute for employee ID and use this API to retrieve the information. You provide access to this Custom Object information when requesting a SLAS token.

    Use Business Manager to set up Custom Object types, including a definition of the object and the values it contains.

    Use the Shopper Custom Objects API to retrieve Custom Object information. You can specify an object type ID as well as a key attribute for the object.

    ## Authentication & Authorization

    To grant access to Custom Object types, include the relevant scope(s) in the client ID used to generate the SLAS token. For details, see the [Scopes Catalog.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/auth-z-scope-catalog.html)

    ```
    sfcc.shopper-custom-objects.{object_type}
    ```

    Important:

    Using an additional scope namespace, you can define exactly which Custom Object types a specific token can access. The requested custom `object_type` must exactly match the `object-type` specified in the scope. Note that SLAS is capable of handling a maximum of 20 Custom Object scopes.

    For example, to limit access to a specific Custom Object type, such as `employee_details`, include it as the `object_type`. In this case, only the `employee_details` custom object type can be accessed:

    ```
    sfcc.shopper-custom-objects.employee_details
    ```

    To grant global access to all Custom Object types, specify:

    ```
    sfcc.shopper-custom-objects
    ```

    For access to multiple Custom Object types, define the applicable scope(s) in the SLAS API client scopes to be included in the SLAS token, for example:

    ```
    sfcc.shopper-custom-objects.employee_details
    sfcc.shopper-custom-objects.employee_performance
    ```

    ## Use Cases

    ### Create and View Custom Object Types

    Custom object types are created in Business Manager:

    1. Navigate to **Administration** -> **Site Development** -> **Custom Object Types**.
    2. In the **Custom Object Type List** section, the available Custom Objects are listed.
    3. To create a new Custom Object type, select **New** and enter the applicable information. This creates the `custom_object_type` information that is in the call to the Shopper Custom Objects API endpoint.

    Additionally, keys that provide additional information can be defined for Custom Object types, for example, a `employee_id` key for an `employee_details` Custom Object type.

    ### Request Custom Object Information

    To request Custom Object type information, the Custom Object type is specified following `custom-objects/` in the API URL:

    ```
    https://{{short-code}}/custom-object/shopper-custom-objects/v1/organizations/{organization_id}/custom-objects/{custom_object_type}/{key}
    ```

    `key` is an optional parameter that retrieves additional Custom Object type information, if available.

    For example, to retrieve the Custom Object type key `employee_id` for the Custom Object type `employee_details`:

    ```
    https://{{short-code}}/custom-object/shopper-custom-objects/v1/organizations/{organization_id}/custom-objects/employee_details/employee_id?siteId=RefArch.
    ```

    ### Use Hooks

    For details working with hooks, see [Extensibility with Hooks.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/extensibility_via_hooks.html)

    ## Constraints

    Custom Object scopes: SLAS is capable of handling a maximum of 20 custom object scopes.

    Custom Objects: Maximum 27 custom objects.

    For additional details, see [Governance and Quotas.](https://developer.salesforce.com/docs/commerce/b2c-commerce/guide/b2c-governance-and-quotas.html)

    ## Troubleshooting

    The Custom Object type requested must exactly match, including case, the information in the SLAS token, for example:

    If the scope is `sfcc.custom-object-type.employee_details`, `employee_details` must match the information in the Shopper Custom Objects request:

    ```
    https://…/custom-object/shopper-custom-objects/v1/organizations/f_ecom_bgmj_stg/custom-objects/employee_details/{key}?siteId`
    ```

    If you do not include the `shopper-custom-objects` as part of the SLAS token request, and you subsequently call the Shopper Custom Objects API, a 401 error is returned.

    If you specify `key` information when no `key` information has been defined for the Custom Object, a 404 response code is returned.
servers:
  - url: https://{shortCode}.api.commercecloud.salesforce.com/custom-object/shopper-custom-objects/v1
    variables:
      shortCode:
        default: shortCode
paths:
  /organizations/{organizationId}/custom-objects/{objectType}/{key}:
    get:
      summary: Read a custom object using its object type ID and its unique key attribute value.
      operationId: getCustomObject
      parameters:
        - $ref: '#/components/parameters/organizationId'
        - $ref: '#/components/parameters/siteId'
        - $ref: '#/components/parameters/locale'
        - $ref: '#/components/parameters/objectType'
        - $ref: '#/components/parameters/key'
      responses:
        '200':
          description: Custom object retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomObject'
              examples:
                CustomObjectResultExample:
                  $ref: '#/components/examples/CustomObjectResultExample'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                MalformedKeyParameter:
                  $ref: '#/components/examples/MalformedKeyParameter'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Unauthorized:
                  $ref: '#/components/examples/Unauthorized'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                CustomObjectNotFound:
                  $ref: '#/components/examples/CustomObjectNotFound'
                ObjectTypeNotFound:
                  $ref: '#/components/examples/ObjectTypeNotFound'
      security:
        - ShopperToken:
            - sfcc.shopper-custom-objects
            - sfcc.shopper-custom-objects.{objectType}
components:
  securitySchemes:
    ShopperToken:
      type: oauth2
      description: "ShopperToken authentication follows the authorization code grant flow, as defined by the OAuth 2.1 standard. Depending on the type of OAuth client (public or private), this authorization flow has further requirements. \nFor a detailed description of the authorization flow, see the [SLAS overview](https://developer.salesforce.com/docs/commerce/commerce-api/references?meta=shopper-login:Summary).\nA shopper token allows you to access the Shopper API endpoints of both OCAPI and the B2C Commerce API. These endpoints can be used to build headless storefronts and other applications.\nThe `ShopperToken` security scheme is a parent of other security schemes, such as `ShopperTokenTsob`. A Shopper API endpoint can require a specific child scheme (`ShopperTokenTsob`, for example) that cannot be accessed with a regular shopper token.\n"
      flows:
        clientCredentials:
          tokenUrl: https://{shortCode}.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/{organizationId}/oauth2/token
          scopes:
            sfcc.shopper-custom-objects: Shopper Custom Objects scope
            sfcc.shopper-custom-objects.{objectType}: Shopper Custom Objects objectType READ ONLY scope
        authorizationCode:
          authorizationUrl: https://{short-code}.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/{organizationId}/oauth2/authorize
          tokenUrl: https://{short-code}.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/{organizationId}/oauth2/token
          scopes:
            sfcc.shopper-custom-objects: Shopper Custom Objects scope
            sfcc.shopper-custom-objects.{objectType}: Shopper Custom Objects objectType READ ONLY scope
  schemas:
    OrganizationId:
      description: An identifier for the organization the request is being made by
      example: f_ecom_zzxy_prd
      type: string
      minLength: 1
      maxLength: 32
    SiteId:
      minLength: 1
      maxLength: 32
      description: The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites
      example: RefArch
      type: string
    LanguageCountry:
      pattern: ^[a-z][a-z]-[A-Z][A-Z]$
      description: A concatenated version of the standard Language and Country codes, combined with a hyphen '`-`'.
      example: en-US
      type: string
    LanguageCode:
      pattern: ^[a-z][a-z]$
      description: A two letter lowercase language code conforming to the [ISO 639-1](https://www.iso.org/iso-639-language-codes.html) standard. Additionally, this may be used to submit requests with the header parameter `Accept-Language`, following [RFC 2616](https://tools.ietf.org/html/rfc2616) & [RFC 1766](https://tools.ietf.org/html/rfc1766).
      example: en
      type: string
    DefaultFallback:
      default: default
      description: A specialized value indicating the system default values for locales.
      example: default
      enum:
        - default
      type: string
    LocaleCode:
      description: A descriptor for a geographical region by both a language and country code. By combining these two, regional differences in a language can be addressed, such as with the request header parameter `Accept-Language` following [RFC 2616](https://tools.ietf.org/html/rfc2616) & [RFC 1766](https://tools.ietf.org/html/rfc1766). This can also just refer to a language code, also RFC 2616/1766 compliant, as a default if there is no specific match for a country. Finally, can also be used to define default behavior if there is no locale specified.
      oneOf:
        - $ref: '#/components/schemas/LanguageCountry'
        - $ref: '#/components/schemas/LanguageCode'
        - $ref: '#/components/schemas/DefaultFallback'
    CustomObject:
      description: Document representing a custom object that contains all defined custom attributes for its object type.
      additionalProperties:
        title: Additional Property Support
        description: |-
          This type supports additional properties passed along with the defined properties of this API.
          To indicate that the properties were defined and expected to be handled as additional properties, they are expected to be prefixed with a `c_`.
          The type will reject any property that does not fit this pattern, only allowing additional properties beginning with the known prefix.
        example: c_trackingId
      properties:
        keyProperty:
          description: The name of the key property for the custom object. This is ignored in input documents.
          type: string
          example: global_key
        keyValueInteger:
          format: int32
          description: The id of the custom object when the type of the key is Integer. This is ignored in input documents.
          type: integer
          example: 1
        keyValueString:
          description: The id of the custom object when the type of the key is String. This is ignored in input documents.
          type: string
          example: '1'
        objectType:
          maxLength: 256
          description: The id of the object type. This is ignored in input documents.
          type: string
          example: Global_String
      type: object
    ErrorResponse:
      type: object
      additionalProperties: true
      properties:
        title:
          description: "A short, human-readable summary of the problem\ntype.  It will not change from occurrence to occurrence of the \nproblem, except for purposes of localization\n"
          type: string
          maxLength: 256
          example: You do not have enough credit
        type:
          description: |
            A URI reference [RFC3986] that identifies the
            problem type.  This specification encourages that, when
            dereferenced, it provide human-readable documentation for the
            problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
            this member is not present, its value is assumed to be
            "about:blank". It accepts relative URIs; this means
            that they must be resolved relative to the document's base URI, as
            per [RFC3986], Section 5.
          type: string
          maxLength: 2048
          example: NotEnoughMoney
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
          example: Your current balance is 30, but that costs 50
        instance:
          description: |
            A URI reference that identifies the specific
            occurrence of the problem.  It may or may not yield further
            information if dereferenced.  It accepts relative URIs; this means
            that they must be resolved relative to the document's base URI, as
            per [RFC3986], Section 5.
          type: string
          maxLength: 2048
          example: /account/12345/msgs/abc
      required:
        - title
        - type
        - detail
  parameters:
    organizationId:
      description: An identifier for the organization the request is being made by
      name: organizationId
      in: path
      required: true
      example: f_ecom_zzxy_prd
      schema:
        $ref: '#/components/schemas/OrganizationId'
    siteId:
      description: The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites.
      name: siteId
      in: query
      required: true
      examples:
        SiteId:
          value: RefArch
      schema:
        $ref: '#/components/schemas/SiteId'
    locale:
      description: A descriptor for a geographical region by both a language and country code. By combining these two, regional differences in a language can be addressed, such as with the request header parameter `Accept-Language` following [RFC 2616](https://tools.ietf.org/html/rfc2616) & [RFC 1766](https://tools.ietf.org/html/rfc1766). This can also just refer to a language code, also RFC 2616/1766 compliant, as a default if there is no specific match for a country. Finally, can also be used to define default behavior if there is no locale specified.
      name: locale
      in: query
      examples:
        LanguageCountry:
          value: en-US
        CountryCode:
          value: US
      schema:
        $ref: '#/components/schemas/LocaleCode'
    objectType:
      name: objectType
      in: path
      required: true
      schema:
        minLength: 1
        type: string
        example: Test_Integer
      description: The object type of custom object.
    key:
      name: key
      in: path
      required: true
      schema:
        minLength: 1
        type: string
        example: '1'
      description: The key to identify the custom object.
  examples:
    CustomObjectResultExample:
      value:
        keyProperty: global_key
        objectType: Global_String
        c_BooleanAttribute: true
        c_DateAttribute: '2015-02-03'
        c_DateTimeAttribute: '2015-02-20T01:00:00.000Z'
        c_EmailAttribute: tralala@gmail.com
        c_HtmlAttribute: "<html>\r\n<head><title>some title</title></head>\r\n<body>the body</body>\r\n</html>"
        c_ImageAttribute: https://whatever/on/demandware.static/-/Sites/default/v0/home/user/images/image.gif
        c_IntegerAttribute: 42
        c_IntegerEnumAttribute: 3
        c_IntegerSetAttribute:
          - 1
          - 2
        c_NumberAttribute: 42
        c_NumberSetAttribute:
          - 1
          - 1.1
        c_PasswordAttribute: UUIG6ydSpJtdBbYDb1JMd7jgiA1rwYmQTzB5AEvz/YjorR6cIl19cu1IN6H/i/Ol
        c_StringAttribute: Tralala
        c_StringEnumAttribute: Value3
        c_StringSetAttribute:
          - string1
          - string2
        c_TextAttribute: This is a text, which is not very meaningful.
    MalformedKeyParameter:
      value:
        title: Malformed Key Parameter
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/malformed-key-parameter
        detail: The format of path parameter 'gdd' for data type 'integer' is invalid.
        value: gdd
        parameter: integer
    Unauthorized:
      value:
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/unauthorized
        title: Unauthorized
        detail: Your access token is invalid or expired and can’t be used to identify a user.
        accessToken: hbGciOiJIUzI1NiIsenR5cCI6Ikp
    CustomObjectNotFound:
      value:
        title: Custom Object Not Found
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/custom-object-not-found
        detail: No custom object with key '2213' for object type 'Test_Integer' could be found.
        key: '2213'
        objectType: Test_Integer
    ObjectTypeNotFound:
      value:
        title: Object Type Not Found
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/object-type-not-found
        detail: No object type with ID 'Test_Integer1' could be found.
        objectType: Test_Integer1
