/*
 * Copyright (c) 2025, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */

/*
 * Auto-generated API names and common dependencies for rollup configuration
 * Generated by: scripts/generateFileList.ts
 *
 * This file contains API names and common dependencies from src/lib directory
 * and is used by rollup.config.js for individual API bundle generation
 */

const apiNames = [
  'helpers',
  'shopperBaskets',
  'shopperBasketsv2',
  'shopperConfigurations',
  'shopperConsents',
  'shopperContext',
  'shopperCustomers',
  'shopperExperience',
  'shopperGiftCertificates',
  'shopperLogin',
  'shopperOrders',
  'shopperPayments',
  'shopperProducts',
  'shopperPromotions',
  'shopperSearch',
  'shopperSeo',
  'shopperStores',
];

const commonDependencies = [
  {input: 'src/lib/clientConfig.ts', file: 'lib/clientConfig.js'},
  {input: 'src/lib/config.ts', file: 'lib/config.js'},
  {input: 'src/lib/importUtil.ts', file: 'lib/importUtil.js'},
  {input: 'src/lib/responseError.ts', file: 'lib/responseError.js'},
  {input: 'src/lib/templateUrl.ts', file: 'lib/templateUrl.js'},
  {input: 'src/lib/version.ts', file: 'lib/version.js'},
];

// Total APIs: 17
// Total common dependencies: 6

export {apiNames, commonDependencies};
